[[main]]
none = "none"

[[main]]
name = "Book Reviews"
pre = "book"
pageRef = "tags/books"
weight = 1

[[main]]
name = "Fiction"
pre = "writing"
pageRef = "tags/short-story"
weight = 2

[[main]]
name = "Tags"
pre = "soundcloud"
pageRef = "tags"
weight = 3

[[main]]
name = "Personal"
pre = "personal"
pageRef = "tags/personal"
weight = 4

[[main]]
name = "RSS"
pre = "rss"
url = "http://thefreudiancouch.com/index.xml"
weight = 5

[[main]]
  name = "Archive"
  url = "/archive"
  weight = 6

[[footer]]
none = "none"
